### ISSUE TITLE
README에 따라 yarn start를 입력해서 website에 들어갔는데 화면이 없습니다.

### ISSUE THREAD

**Issue by Lin-CX** [art-mate/ame#14]
## 🤷 이슈 내용

무슨 이슈인가요?
README에 따라 yarn start를 입력해서 website에 들어갔는데 화면이 없습니다.
## ✨ 기대 결과

어떤 결과물을 원하시나요?
웹화면을 정상적으로 나온다.
## 📸 스크린샷

이슈에 해당하는 부분을 보여주세요.
![image](https://user-images.githubusercontent.com/58055837/98808532-9d086c00-245f-11eb-884c-dfb6024a66b7.png)

**Comment by ginger-kang** [comment]
@Lin-CX Inspector말고 Console창 한번 보여주시겠어요?

**Comment by Lin-CX** [comment]
> @Lin-CX Inspector말고 Console창 한번 보여주시겠어요?

![image](https://user-images.githubusercontent.com/58055837/98809833-8fec7c80-2461-11eb-9d4f-536e4087f92d.png)

**Comment by Lin-CX** [comment]
> @Lin-CX Inspector말고 Console창 한번 보여주시겠어요?

![image](https://user-images.githubusercontent.com/58055837/98809923-b3172c00-2461-11eb-84af-e66d137d0c23.png)

**Comment by ginger-kang** [comment]
@Lin-CX 
아하 `.env`파일이 없기 때문에 firebase config설정이 안되어 있어서 그런것같아요!
프로젝트 루트 폴더에서 `.env`파일 생성하시고 보내드리는 설정 값들 작성하시면 될 것 같습니다.
